api = "0.2"

[buildpack]
  id = "entrypoint"
  name = "Entrypoint Buildpack"
  version = "0.0.2"

[metadata]
include_files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
